version: '3'

services:
  app1:
    build: ./app1
    ports:
      - "5001:5001"
    networks:
      - my_network

  app2:
    build: ./app2
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
